services:
  - type: web
    name: dashboard-diretoria-l
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && cd server && npm install
    startCommand: cd server && node --max-old-space-size=460 server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPLOAD_TOKEN
        value: sjcomercial
      - key: RENDER_EXTERNAL_URL
        value: https://dashboard-diretoria-l-lwkm.onrender.com
      - key: VTEX_ACCOUNT
        value: sjdigital
      - key: VTEX_APP_KEY
        sync: false
      - key: VTEX_APP_TOKEN
        sync: false
